### ISSUE TITLE
node-1 provisioning error (node-1: stdin: is not a tty)

### ISSUE THREAD

**Issue by miloslavPansky** [denverdino/docker-swarm-mode-vagrant#1]
If provisioning of node-1 starts, i get this error message:

```
node-1: Guest Additions Version: 4.3.36
node-1: VirtualBox Version: 5.0
```

==> node-1: Setting hostname...
==> node-1: Configuring and enabling network interfaces...
==> node-1: Mounting shared folders...
    node-1: /vagrant => /home/mips/vagrant/docker_swarm_mode/docker-swarm-mode-vagrant
==> node-1: Running provisioner: shell...
    node-1: Running: inline script
==> node-1: stdin: is not a tty
==> node-1: curl: (52) Empty reply from server
==> node-1: docker: unrecognized service
==> node-1: gpasswd: group 'docker' does not exist in /etc/group
==> node-1: /vagrant/provision-manager.sh: line 18: docker: command not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

After this error vagrant up command completely fails. 

Thanks for help.
MP

**Comment by denverdino** [comment]
Thanks for point it out. It is due to it is using the Aliyun mirror by default which is designed for Chinese user. 

I make some changes to disable mirror and and make it work with the 1.12GA version
